"""Add is_visible to Assignment

Revision ID: 18179b3c35cf
Revises: 73859950bdbe
Create Date: 2026-08-17 19:08:14.340883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18179b3c35cf'
down_revision = '73859950bdbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_visible', sa.Boolean(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('is_visible')

    # ### end Alembic commands ###
