"""Add grade to Submission

Revision ID: 73859950bdbe
Revises: 5baa5636caef
Create Date: 2026-08-17 18:02:32.143461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73859950bdbe'
down_revision = '5baa5636caef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('feedback', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('feedback')
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
